name       : qrencode
version    : 3.4.4
release    : 2
source     :
    - https://fukuchi.org/works/qrencode/qrencode-3.4.4.tar.bz2 : efe5188b1ddbcbf98763b819b146be6a90481aac30cfc8d858ab78a19cde1fa5
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Libqrencode is a C library for encoding data in a QR Code symbol
description: |
    Libqrencode is a C library for encoding data in a QR Code symbol
builddeps  :
    - pkgconfig(libpng)
    - pkgconfig(sdl2)
libsplit   : no
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
