name       : qrencode
version    : 4.0.2
release    : 3
source     :
    - https://fukuchi.org/works/qrencode/qrencode-4.0.2.tar.bz2 : c9cb278d3b28dcc36b8d09e8cad51c0eca754eb004cb0247d4703cb4472b58b4
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Libqrencode is a C library for encoding data in a QR Code symbol
description: |
    Libqrencode is a C library for encoding data in a QR Code symbol
builddeps  :
    - pkgconfig(libpng)
    - pkgconfig(sdl2)
libsplit   : no
setup      : |
    %configure --with-tests
build      : |
    %make
install    : |
    %make_install
check      : |
    cd tests
    sh test_all.sh
