name       : qrencode
version    : 4.0.2
release    : 6
source     :
    - https://github.com/fukuchi/libqrencode/archive/v4.0.2.tar.gz : 43091fea4752101f0fe61a957310ead10a7cb4b81e170ce61e5baa73a6291ac2
homepage   : https://fukuchi.org/works/qrencode/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Libqrencode is a C library for encoding data in a QR Code symbol
description: |
    Libqrencode is a fast and compact library for encoding data in a QR Code symbol, a 2D symbology that can be scanned by handy terminals such as a mobile phone with CCD. The capacity of QR Code is up to 7000 digits or 4000 characters and has high robustness.
builddeps  :
    - pkgconfig(libpng)
    - pkgconfig(sdl2)
libsplit   : no
setup      : |
    %reconfigure --with-tests
build      : |
    %make
install    : |
    %make_install
check      : |
    cd tests
    sh test_all.sh
